version: '3'
services: 
  manager: 
    build: 
      context: "./manager"
    #image: "config:latest"
    environment:
      - POSTGRES_USER=PGUSER
      - POSTGRES_PASSWORD=PGPASSWORD
      - POSTGRES_DB=PGDB
      - CSV_FILENAME=data.csv
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=PGUSER
      - POSTGRES_PASSWORD=PGPASSWORD
      - POSTGRES_DB=PGDB
    ports: 
      - "8001:5432" 